### ISSUE TITLE
can't recive error response body (lists.createTask() method)

### ISSUE THREAD

**Issue by alexander-mart** [ComfortablyCoding/clickup.js#38] opened 2023-09-17 14:26 UTC
Output:
```
error.response
error.response.body undefined
error.response.statusCode 200
error.response.headers {
...
```

```ts
// index.ts:

import 'dotenv-flow/config'

// const { Clickup } = require('clickup.js');
import { Clickup } from 'clickup.js'
const clickup = new Clickup(process.env.CLICKUP_TOKEN)

const list_id = '162338452';

(async () => {
  try {
    // create a task on a list
    const taskData = {
      name: 'New Task Name',
      description: 'New Task Description',
    };

    const { body } = await clickup.lists.createTask(list_id, taskData);
    console.log(body);
  } catch (error) {
    if (error.response) {
      // The request was made and the server responded with a status code
      // that falls out of the range of 2xx
      console.log('error.response');
      console.log('error.response.body', error.response.body);
      console.log('error.response.statusCode',error.response.statusCode);
      //   console.log(error.response.headers);
      console.log('error.response.headers', error.response.headers);
    } else if (error.request) {
      // The request was made but no response was received
      console.log('error.request');
      console.log(error.request);
      //   console.log(error.request);
    } else {
      // Something happened in setting up the request that triggered an Error
      console.log('Error', error.message);
    }
    console.log(error.options);
  }
})();
```

**Comment by ComfortablyCoding** [comment] 2023-09-19 11:17
Strange, a 200 status response should not result in any error.

I will see if I can reproduce this.

**Comment by ComfortablyCoding** [comment] 2024-02-14 02:32
I cannot reproduce this issue with the provided steps, I get a success response for the request. I would log the entire error object and see if you an pinpoint the issues from there. I am closing for now, happy to reopen this if reproducible steps are provided.

**Closed by ComfortablyCoding** 2024-02-14 02:32 UTC
